import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MobileWarning } from "@/components/mobile-warning";
import { SileoToaster } from "@/components/sileo-toaster";
import { KeyboardProvider } from "@/providers/keyboard.context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background font-sans text-foreground">
        <SileoToaster />
        <MobileWarning />
        <KeyboardProvider>{children}</KeyboardProvider>
      </body>
    </html>
  );
}
