import { metalClickSound } from "@/lib/metal-click"

export type KeyConfig = {
  code: string
  label: string
  sound: string
  volume?: number
  pitch?: number
  modifier?: boolean
  size?: "normal" | "wide" | "extra-wide" | "space"
}

function key(
  id: string,
  label: string,
  options: Partial<Omit<KeyConfig, "code" | "label">> = {}
): [string, KeyConfig] {
  return [
    id,
    {
      code: id,
      label,
      sound: metalClickSound.name,
      volume: 1,
      pitch: 1,
      ...options,
    },
  ]
}

const KEY_ENTRIES: [string, KeyConfig][] = [
  key("backquote", "`"),
  key("1", "1"),
  key("2", "2"),
  key("3", "3"),
  key("4", "4"),
  key("5", "5"),
  key("6", "6"),
  key("7", "7"),
  key("8", "8"),
  key("9", "9"),
  key("0", "0"),
  key("minus", "-"),
  key("equal", "="),
  key("backspace", "Backspace", { modifier: true, size: "extra-wide" }),
  key("tab", "Tab", { modifier: true, size: "wide" }),
  key("q", "Q"),
  key("w", "W"),
  key("e", "E"),
  key("r", "R"),
  key("t", "T"),
  key("y", "Y"),
  key("u", "U"),
  key("i", "I"),
  key("o", "O"),
  key("p", "P"),
  key("bracketleft", "["),
  key("bracketright", "]"),
  key("backslash", "\\"),
  key("capslock", "Caps", { modifier: true, size: "wide" }),
  key("a", "A"),
  key("s", "S"),
  key("d", "D"),
  key("f", "F"),
  key("g", "G"),
  key("h", "H"),
  key("j", "J"),
  key("k", "K"),
  key("l", "L"),
  key("semicolon", ";"),
  key("quote", "'"),
  key("enter", "Enter", { modifier: true, size: "wide" }),
  key("shift-l", "Shift", { modifier: true, size: "wide" }),
  key("z", "Z"),
  key("x", "X"),
  key("c", "C"),
  key("v", "V"),
  key("b", "B"),
  key("n", "N"),
  key("m", "M"),
  key("comma", ","),
  key("period", "."),
  key("slash", "/"),
  key("shift-r", "Shift", { modifier: true, size: "wide" }),
  key("control-l", "Ctrl", { modifier: true, size: "wide" }),
  key("alt-l", "Alt", { modifier: true }),
  key("meta-l", "Cmd", { modifier: true }),
  key("space", "Space", { modifier: true, size: "space" }),
  key("meta-r", "Cmd", { modifier: true }),
  key("alt-r", "Alt", { modifier: true }),
  key("control-r", "Ctrl", { modifier: true, size: "wide" }),
  key("delete", "Del", { modifier: true }),
]

export const KEY_CONFIGS: Record<string, KeyConfig> =
  Object.fromEntries(KEY_ENTRIES)

export const KEYBOARD_LAYOUT: string[][] = [
  [
    "backquote",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "minus",
    "equal",
    "backspace",
  ],
  [
    "tab",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    "bracketleft",
    "bracketright",
    "backslash",
  ],
  [
    "capslock",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "semicolon",
    "quote",
    "enter",
  ],
  [
    "shift-l",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
    "comma",
    "period",
    "slash",
    "shift-r",
  ],
  [
    "control-l",
    "alt-l",
    "meta-l",
    "space",
    "meta-r",
    "alt-r",
    "control-r",
  ],
]

const CODE_TO_KEY_ID: Record<string, string> = {
  Backquote: "backquote",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",
  Minus: "minus",
  Equal: "equal",
  Backspace: "backspace",
  Tab: "tab",
  KeyQ: "q",
  KeyW: "w",
  KeyE: "e",
  KeyR: "r",
  KeyT: "t",
  KeyY: "y",
  KeyU: "u",
  KeyI: "i",
  KeyO: "o",
  KeyP: "p",
  BracketLeft: "bracketleft",
  BracketRight: "bracketright",
  Backslash: "backslash",
  CapsLock: "capslock",
  KeyA: "a",
  KeyS: "s",
  KeyD: "d",
  KeyF: "f",
  KeyG: "g",
  KeyH: "h",
  KeyJ: "j",
  KeyK: "k",
  KeyL: "l",
  Semicolon: "semicolon",
  Quote: "quote",
  Enter: "enter",
  ShiftLeft: "shift-l",
  KeyZ: "z",
  KeyX: "x",
  KeyC: "c",
  KeyV: "v",
  KeyB: "b",
  KeyN: "n",
  KeyM: "m",
  Comma: "comma",
  Period: "period",
  Slash: "slash",
  ShiftRight: "shift-r",
  ControlLeft: "control-l",
  AltLeft: "alt-l",
  MetaLeft: "meta-l",
  Space: "space",
  MetaRight: "meta-r",
  AltRight: "alt-r",
  ControlRight: "control-r",
  Delete: "delete",
}

export function codeToKeyId(code: string): string | null {
  return CODE_TO_KEY_ID[code] ?? null
}
